AllCops:
  TargetRailsVersion: 8.0.1
  Documentation:
    Enabled: false
  Exclude:
    - db/**/*
    - config/**/*
    - bin/*
    - vendor/**/*
    - node_modules/**/*

plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-capybara
  - rubocop-factory_bot

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 50

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 10

RSpec/MultipleMemoizedHelpers:
  Max: 10

Metrics/BlockLength:
  Exclude:
    - .active_record_doctor.rb
    - .database_consistency.yml
