AllCops:
  TargetRailsVersion: 8.0.1
  Documentation:
    Enabled: false
  Exclude:
    - db/**/*
    - config/**/*
    - bin/*

plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-capybara

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/MethodLength:
  Max: 50

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Max: 5
