AllCops:
  TargetRailsVersion: 8.0.1
  Documentation:
    Enabled: false
  Exclude:
    - db/**/*
    - config/**/*
    - bin/*
    - test/**/*

plugins: rubocop-rails

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
