services:
  database:
    image: postgis/postgis:16-3.5-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
      - db-data:/var/lib.postgresql/data

  webapp:
    image: event_man
    build:
      context: .
      args:
        RAILS_SECRET_KEY_BASE: ${RAILS_SECRET_KEY_BASE}
        RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_NAME: ${DB_NAME}
      DB_URL: ${DB_URL}
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 3000:3000

volumes:
  db-data:
